language: python

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7d967d9679efbbc43466
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

install:
  - pip install -r requirements.txt

before_script:
  - ./scripts/ci/setup_git.sh

script:
  - ./scripts/build-docs.sh

after_success:
  - ./scripts/ci/deploy-docs.sh
